// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6hLob0ji-ll-L-b4_5FC4nDLzgOuZu6M',
    appId: '1:192498903739:web:f2355efeb7386ce497d79e',
    messagingSenderId: '192498903739',
    projectId: 'project-apk-shelter',
    authDomain: 'project-apk-shelter.firebaseapp.com',
    storageBucket: 'project-apk-shelter.firebasestorage.app',
    measurementId: 'G-HSWZGH6CNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlx-b9Q_LPA4_NnlpEcira3VL4gnHTJMo',
    appId: '1:192498903739:android:cd67355aec001a7397d79e',
    messagingSenderId: '192498903739',
    projectId: 'project-apk-shelter',
    storageBucket: 'project-apk-shelter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWxewhl0YAwL1PxttBSZnd4AzIWp14ECU',
    appId: '1:192498903739:ios:be3052083cef304597d79e',
    messagingSenderId: '192498903739',
    projectId: 'project-apk-shelter',
    storageBucket: 'project-apk-shelter.firebasestorage.app',
    iosBundleId: 'com.example.projectApkShelter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWxewhl0YAwL1PxttBSZnd4AzIWp14ECU',
    appId: '1:192498903739:ios:be3052083cef304597d79e',
    messagingSenderId: '192498903739',
    projectId: 'project-apk-shelter',
    storageBucket: 'project-apk-shelter.firebasestorage.app',
    iosBundleId: 'com.example.projectApkShelter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6hLob0ji-ll-L-b4_5FC4nDLzgOuZu6M',
    appId: '1:192498903739:web:129e8d02e45a05e797d79e',
    messagingSenderId: '192498903739',
    projectId: 'project-apk-shelter',
    authDomain: 'project-apk-shelter.firebaseapp.com',
    storageBucket: 'project-apk-shelter.firebasestorage.app',
    measurementId: 'G-034CTXEJ1S',
  );
}
